version : 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run test:e2e:ci
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: bash .sh/deploy.sh
workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v\d\.\d\.\d/
            branches:
              ignore: /.*/
